apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-executor
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-workflow-executor
subjects:
- kind: ServiceAccount
  name: argo-workflow
roleRef:
  kind: Role
  name: argo-executor
  apiGroup: rbac.authorization.k8s.io
