---
# Generic AMQP publish job
# Publishes payload from 'amqp-payload' configmap to RabbitMQ
#
# Usage:
#   1. Create configmap: kubectl create configmap amqp-payload --from-file=body.json=<payload-file>
#   2. Apply this job: kubectl apply -f amqp-publish-once.yaml
#   3. Wait: kubectl wait --for=condition=complete job/amqp-publish-once
#
apiVersion: batch/v1
kind: Job
metadata:
  name: amqp-publish-once
  namespace: devseed-staging
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: publish
          image: python:3.11-slim
          command:
            - /bin/bash
            - -c
            - |
              set -e
              pip install -q pika
              cat <<'PUBLISH_SCRIPT' > /tmp/publish.py
              import json
              import os
              import pika

              with open('/payload/body.json') as f:
                  payload = json.load(f)

              credentials = pika.PlainCredentials(
                  os.environ['RABBITMQ_USERNAME'],
                  os.environ['RABBITMQ_PASSWORD']
              )
              parameters = pika.ConnectionParameters(
                  host='rabbitmq.core.svc.cluster.local',
                  port=5672,
                  credentials=credentials
              )

              connection = pika.BlockingConnection(parameters)
              channel = connection.channel()

              routing_key = f"eopf.item.found.{payload['collection']}"

              channel.basic_publish(
                  exchange='eopf_items',
                  routing_key=routing_key,
                  body=json.dumps(payload),
                  properties=pika.BasicProperties(
                      content_type='application/json',
                      delivery_mode=2  # persistent
                  )
              )

              print(f"✅ Published to exchange=eopf_items, routing_key={routing_key}")
              print(f"📦 Payload: {json.dumps(payload, indent=2)}")

              connection.close()
              PUBLISH_SCRIPT

              python /tmp/publish.py
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          volumeMounts:
            - name: payload
              mountPath: /payload
              readOnly: true
      volumes:
        - name: payload
          configMap:
            name: amqp-payload
