---
# Direct S1 GRD test workflow submission
# Uses the geozarr-pipeline WorkflowTemplate
#
# Usage: kubectl create -f run-s1-test.yaml
#
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: geozarr-s1-test-
  namespace: devseed-staging
  labels:
    workflows.argoproj.io/workflow-template: geozarr-pipeline
    pipeline.eopf/collection: sentinel-1-l1-grd-dp-test
    pipeline.eopf/test: s1-e2e-dask
spec:
  workflowTemplateRef:
    name: geozarr-pipeline
  arguments:
    parameters:
      - name: source_url
        value: "https://stac.core.eopf.eodc.eu/collections/sentinel-1-l1-grd/items/S1A_IW_GRDH_1SDV_20251005T054153_20251005T054218_061286_07A523_036F"
      - name: item_id
        value: "S1A_IW_GRDH_1SDV_20251005T054153_20251005T054218_061286_07A523_036F"
      - name: register_collection
        value: "sentinel-1-l1-grd-dp-test"
      - name: stac_api_url
        value: "https://api.explorer.eopf.copernicus.eu/stac"
      - name: raster_api_url
        value: "https://api.explorer.eopf.copernicus.eu/raster"
      - name: s3_endpoint
        value: "https://s3.de.io.cloud.ovh.net"
      - name: s3_output_bucket
        value: "esa-zarr-sentinel-explorer-fra"
      - name: s3_output_prefix
        value: "tests-output"
      - name: pipeline_image_version
        value: "v26"
